name: webview_test
description: "WebView-to-Flutter bridge demo app"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  
  # WebView for Android/Windows
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.12.0
  
  # Permissions
  permission_handler: ^12.0.1
  
  # Device features
  geolocator: ^14.0.2
  camera: ^0.12.0+1
  path_provider: ^2.1.5

  # Maps
  google_maps_flutter: ^2.9.0
  geocoding: ^4.0.0
  flutter_launcher_icons: ^0.14.4
  image: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/web/

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/gesit3_white_round.png"